### ISSUE TITLE
Please provide the code used in experiment

### ISSUE THREAD

**Issue by ALEX13679173326** [continental/image-statistics-matching#1]
There are some experiments using Faster R-CNN in the paper. Can you provide the code used in the experiments?

**Comment by aabramovrepo** [comment]
> There are some experiments using Faster R-CNN in the paper. Can you provide the code used in the experiments?

we are planning to release our training pipelines during this year

**Comment by ALEX13679173326** [comment]
OK！Thanks！
I'm also wondering how to generate a synthetic data set(or domain adapted training dataset). Is it randomly extracting images from the source domain and target domain?Can you give me the code for this?

**Comment by aabramovrepo** [comment]
it is explained in the paper (Section 4)
